### ISSUE TITLE
Quotes aren't escaped correctly

### ISSUE THREAD

**Issue by ehiggs** [tafia/quick-csv#2]
quick-csv doesn't escape quotes correctly. It treats `"foo""bar"` as `foo""bar` when it should be parsed as `foo"bar"` as per item 7 in [RFC-4180](https://www.rfc-editor.org/rfc/rfc4180.txt). This is likely a known issue since the tests covering this are commented out.

**Comment by tafia** [comment]
Thanks for reporting the issue.
Should be fixed soon

**Comment by tafia** [comment]
Should be fixed now.

Just to be certain,which test exactly did you refer to ?
I think I've deleted many tests, some of them because I thought were not in line with specs. Please let me know if I shouldn't have done it for some of them.

In particular:
- escaped quotes without the column being in quotes (just added a fail test for this)
- empty lines even for 1 column csv were discarded
- `\r` being a line separator: for me only `\n` and `\r\n` as valid _per default_
